name: material_design
description: "The fastest path to consistent Material Design UIs in Flutter. Build beautiful apps aligned with official metrics and guidelines using a powerful set of ready-to-use design tokens and helper widgets."
version: 0.28.1
# author: Kevin Kobori <https://www.linkedin.com/in/kevin-kobori/>
homepage:
repository: https://github.com/fluttely/material_design
issue_tracker: https://github.com/fluttely/material_design/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
